management:
  security:
    enabled: false 

security:
  basic:
    enabled: false

spring:
  cloud:
    service:
      registrationMethod: direct

logging:
  level:
    io:
      pivotal:
        training: INFO 
